/**
 * Centralized Domain & Operational Event Types for Realtime SSE Delivery.
 */
export enum RealtimeEventType {
  BOOKING_CREATED = 'BOOKING_CREATED',
  BOOKING_CONFIRMED = 'BOOKING_CONFIRMED',
  BOOKING_CANCELLED = 'BOOKING_CANCELLED',
  PAYMENT_COMPLETED = 'PAYMENT_COMPLETED',
  PAYMENT_FAILED = 'PAYMENT_FAILED',
  CHECKED_IN = 'CHECKED_IN',
  CHECKED_OUT = 'CHECKED_OUT',
  NOTIFICATION_CREATED = 'NOTIFICATION_CREATED',
  HOTEL_STATUS_CHANGED = 'HOTEL_STATUS_CHANGED',
  USER_STATUS_CHANGED = 'USER_STATUS_CHANGED',
  MANAGER_ASSIGNMENT_CHANGED = 'MANAGER_ASSIGNMENT_CHANGED',
  HEARTBEAT = 'HEARTBEAT',
}
