export enum UserRole {
  CUSTOMER = 'CUSTOMER',
  HOTEL_MANAGER = 'HOTEL_MANAGER',
  MANAGER = 'HOTEL_MANAGER',
  ADMIN = 'ADMIN',
}

export enum UserStatus {
  ACTIVE = 'ACTIVE',
  SUSPENDED = 'SUSPENDED',
  DISABLED = 'DISABLED',
  PENDING_VERIFICATION = 'PENDING_VERIFICATION',
}
