import { Hotel, Booking, UserProfile } from '../types';

export const INITIAL_USER: UserProfile = {
  id: 'usr_cust_01',
  name: 'Ananya Sharma',
  email: 'ananya.sharma@example.com',
  phone: '+91 98765 43210',
  role: 'CUSTOMER',
  memberTier: 'Platinum Sanctuary',
  avatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&w=200&q=80',
  joinedDate: 'January 2025',
};

export const MOCK_HOTELS: Hotel[] = [
  {
    id: 'htl_chennai_01',
    name: 'Grand Hyatt Chennai',
    slug: 'grand-hyatt-chennai',
    tagline: 'Urban coastal sanctuary of contemporary elegance and world-class dining',
    description: 'Set amidst landscaped tropical palms in central Chennai, Grand Hyatt Chennai pairs legendary South Indian hospitality with soaring contemporary architecture. Featuring an expansive lagoon swimming pool, an award-winning Ayurvedic spa, and five artisanal dining venues, each guest room is an oasis of calm respite from the bustling coastal metropolis.',
    city: 'Chennai',
    state: 'Tamil Nadu',
    country: 'India',
    address: '32 Jawaharlal Nehru Road, Anna Nagar, Chennai',
    postalCode: '600032',
    starRating: 5,
    averageRating: 4.85,
    totalReviews: 324,
    distanceToCenter: '1.4 km from City Center',
    nearbyAttraction: '12 mins to Marina Beach',
    minPrice: 6500,
    checkInTime: '14:00',
    checkOutTime: '12:00',
    cancellationPolicy: 'Free cancellation up to 48 hours prior to check-in. 1-night penalty thereafter.',
    heroImage: 'https://images.unsplash.com/photo-1566073771259-6a8506099945?auto=format&fit=crop&w=1200&q=80',
    images: [
      'https://images.unsplash.com/photo-1566073771259-6a8506099945?auto=format&fit=crop&w=1000&q=80',
      'https://images.unsplash.com/photo-1582719478250-c89cae4dc85b?auto=format&fit=crop&w=1000&q=80',
      'https://images.unsplash.com/photo-1618773928121-c32242e63f39?auto=format&fit=crop&w=1000&q=80',
      'https://images.unsplash.com/photo-1571896349842-33c89424de2d?auto=format&fit=crop&w=1000&q=80',
      'https://images.unsplash.com/photo-1540555700478-4be289fbecef?auto=format&fit=crop&w=1000&q=80',
    ],
    amenities: [
      'Free High-Speed WiFi',
      'Outdoor Lagoon Pool',
      'Full-Service Wellness Spa',
      'Complimentary Gourmet Breakfast',
      'Fitness Center 24/7',
      'Airport Limousine Transfer',
      'Fine-Dining Restaurants',
      '24-Hour Concierge',
    ],
    roomTypes: [
      {
        id: 'rt_ghc_01',
        hotelId: 'htl_chennai_01',
        name: 'Deluxe City View King',
        description: 'Soothing natural oak textures, plush king-sized signature bedding, and panoramic glass vistas overlooking the city skyline.',
        basePrice: 6500,
        maxGuests: 2,
        bedType: '1 King Bed',
        roomSize: '42 m² / 450 sq ft',
        totalRooms: 15,
        availableRooms: 6,
        images: [
          'https://images.unsplash.com/photo-1618773928121-c32242e63f39?auto=format&fit=crop&w=800&q=80',
          'https://images.unsplash.com/photo-1590490360182-c33d57733427?auto=format&fit=crop&w=800&q=80',
        ],
        amenities: ['4K Smart TV', 'Italian Marble Bath', 'Espresso Machine', 'Work Desk', 'Rain Shower'],
        hasFreeCancellation: true,
        breakfastIncluded: true,
      },
      {
        id: 'rt_ghc_02',
        hotelId: 'htl_chennai_01',
        name: 'Grand Ocean Horizon Suite',
        description: 'Expanded executive suite featuring a dedicated parlor lounge, private coastal viewing terrace, and deep soaking freestanding tub.',
        basePrice: 11200,
        maxGuests: 3,
        bedType: '1 King Bed + Daybed',
        roomSize: '68 m² / 730 sq ft',
        totalRooms: 6,
        availableRooms: 2, // low inventory indicator
        images: [
          'https://images.unsplash.com/photo-1582719478250-c89cae4dc85b?auto=format&fit=crop&w=800&q=80',
          'https://images.unsplash.com/photo-1591088398332-8a7791972843?auto=format&fit=crop&w=800&q=80',
        ],
        amenities: ['Terrace Balcony', 'Club Lounge Access', 'Soaking Bathtub', 'Butler Service', 'Walk-in Wardrobe'],
        hasFreeCancellation: true,
        breakfastIncluded: true,
      },
      {
        id: 'rt_ghc_03',
        hotelId: 'htl_chennai_01',
        name: 'Premier Twin Garden View',
        description: 'Quiet sanctuary facing tranquil manicured palms and reflecting pools, tailored for colleagues or companion travelers.',
        basePrice: 7200,
        maxGuests: 2,
        bedType: '2 Queen Beds',
        roomSize: '46 m² / 495 sq ft',
        totalRooms: 10,
        availableRooms: 5,
        images: [
          'https://images.unsplash.com/photo-1595526114035-0d45ed16cfbf?auto=format&fit=crop&w=800&q=80',
        ],
        amenities: ['Garden View', 'Ergonomic Workspace', 'Premium Minibar', 'Double Vanities'],
        hasFreeCancellation: true,
        breakfastIncluded: false,
      },
    ],
    reviews: [
      {
        id: 'rev_ghc_01',
        hotelId: 'htl_chennai_01',
        bookingId: 'BK-104921',
        customerName: 'Rohit Balakrishnan',
        rating: 5,
        title: 'Exemplary service and peaceful coastal escape',
        comment: 'From the warm welcome drink to the impeccable cleanliness in the Ocean Horizon suite, Grand Hyatt exceeded every expectation. The breakfast buffet has an astonishing South Indian dosa bar alongside artisan pastries.',
        stayDate: 'August 2026',
        roomTypeName: 'Grand Ocean Horizon Suite',
        createdAt: '2026-08-22',
        categories: { cleanliness: 5, staff: 5, comfort: 5, value: 4.8, location: 4.9 },
      },
      {
        id: 'rev_ghc_02',
        hotelId: 'htl_chennai_01',
        bookingId: 'BK-104922',
        customerName: 'Meera Nambiar',
        rating: 5,
        title: 'Unrivaled spa treatments and calm atmosphere',
        comment: 'The serene pool and Ayurvedic treatments made our anniversary getaway truly unforgettable. Check-in was swift and the room acoustics were wonderfully quiet.',
        stayDate: 'July 2026',
        roomTypeName: 'Deluxe City View King',
        createdAt: '2026-07-15',
        categories: { cleanliness: 5, staff: 4.9, comfort: 5, value: 4.7, location: 4.8 },
      },
    ],
  },
  {
    id: 'htl_mumbai_02',
    name: 'The Taj Mahal Palace',
    slug: 'the-taj-mahal-palace-mumbai',
    tagline: 'India’s legendary heritage icon overlooking the Gateway of India',
    description: 'Standing majestically opposite the Gateway of India, The Taj Mahal Palace is a living masterpiece of Moorish, Oriental, and Florentine architectural grandeur. Opened in 1903, this legendary hotel offers royal white-gloved hospitality, nine renowned international restaurants, and museum-caliber antique collections throughout its gilded corridors.',
    city: 'Mumbai',
    state: 'Maharashtra',
    country: 'India',
    address: 'Apollo Bunder, Colaba, Mumbai',
    postalCode: '400001',
    starRating: 5,
    averageRating: 4.96,
    totalReviews: 842,
    distanceToCenter: 'Heart of Historic Colaba',
    nearbyAttraction: 'Direct Gateway of India waterfront',
    minPrice: 18500,
    checkInTime: '14:00',
    checkOutTime: '12:00',
    cancellationPolicy: 'Free cancellation up to 48 hours prior to check-in.',
    heroImage: 'https://images.unsplash.com/photo-1542314831-068cd1dbfeeb?auto=format&fit=crop&w=1200&q=80',
    images: [
      'https://images.unsplash.com/photo-1542314831-068cd1dbfeeb?auto=format&fit=crop&w=1000&q=80',
      'https://images.unsplash.com/photo-1578683010236-d716f9a3f461?auto=format&fit=crop&w=1000&q=80',
      'https://images.unsplash.com/photo-1566665797739-1674de7a421a?auto=format&fit=crop&w=1000&q=80',
      'https://images.unsplash.com/photo-1520250497591-112f2f40a3f4?auto=format&fit=crop&w=1000&q=80',
    ],
    amenities: [
      'Heritage Architecture',
      'Arabian Sea Views',
      'Jiva Grand Spa',
      'Swimming Pool with Colonnade',
      'Butler Service',
      'Valet Parking',
      '9 Signature Restaurants',
      'Curated Art Tours',
    ],
    roomTypes: [
      {
        id: 'rt_taj_01',
        hotelId: 'htl_mumbai_02',
        name: 'Heritage Palace Wing Room',
        description: 'Authentic 1903 heritage charm, handwoven carpets, high vaulted ceilings, and views overlooking the harbor or landscaped pool gardens.',
        basePrice: 18500,
        maxGuests: 2,
        bedType: '1 Royal King Bed',
        roomSize: '48 m² / 515 sq ft',
        totalRooms: 12,
        availableRooms: 3,
        images: [
          'https://images.unsplash.com/photo-1566665797739-1674de7a421a?auto=format&fit=crop&w=800&q=80',
        ],
        amenities: ['Sea View', 'Heritage Antiques', 'Clawfoot Tub', 'Signature Tea Set', 'High-Speed WiFi'],
        hasFreeCancellation: true,
        breakfastIncluded: true,
      },
      {
        id: 'rt_taj_02',
        hotelId: 'htl_mumbai_02',
        name: 'Tower Sea Facing Suite',
        description: 'Breathtaking 180-degree unobstructed panoramas of Mumbai Harbour and the Arabian Sea with dedicated living salon.',
        basePrice: 32000,
        maxGuests: 3,
        bedType: '1 King Bed',
        roomSize: '82 m² / 880 sq ft',
        totalRooms: 5,
        availableRooms: 1, // Only 1 left!
        images: [
          'https://images.unsplash.com/photo-1578683010236-d716f9a3f461?auto=format&fit=crop&w=800&q=80',
        ],
        amenities: ['180° Sea Panorama', 'Private Dining Area', 'Complimentary High Tea', 'Personal Butler'],
        hasFreeCancellation: true,
        breakfastIncluded: true,
      },
    ],
    reviews: [
      {
        id: 'rev_taj_01',
        hotelId: 'htl_mumbai_02',
        bookingId: 'BK-890123',
        customerName: 'Siddharth Roy',
        rating: 5,
        title: 'The pinnacle of Indian hospitality',
        comment: 'Staying at the Taj Palace is a timeless experience. The heritage walk, the view of the Gateway from breakfast, and the attentiveness of the team are simply world-class.',
        stayDate: 'September 2026',
        roomTypeName: 'Heritage Palace Wing Room',
        createdAt: '2026-09-18',
        categories: { cleanliness: 5, staff: 5, comfort: 5, value: 4.9, location: 5 },
      },
    ],
  },
  {
    id: 'htl_udaipur_03',
    name: 'The Oberoi Udaivilas',
    slug: 'the-oberoi-udaivilas-udaipur',
    tagline: 'Palatial luxury on the tranquil banks of Lake Pichola',
    description: 'Conceived as a grand Rajasthani royal palace, The Oberoi Udaivilas sprawls over 50 acres on the banks of historic Lake Pichola. Interconnected by rambling courtyards, glistening hand-carved stone domes, and semicircular infinity pools reflecting the ancient City Palace across the water.',
    city: 'Udaipur',
    state: 'Rajasthan',
    country: 'India',
    address: 'Haridas Ji Ki Magri, Mulla Talai, Udaipur',
    postalCode: '313001',
    starRating: 5,
    averageRating: 4.98,
    totalReviews: 512,
    distanceToCenter: 'Direct Lake Pichola Shoreline',
    nearbyAttraction: 'Private Shikara boat to City Palace',
    minPrice: 34000,
    checkInTime: '14:00',
    checkOutTime: '12:00',
    cancellationPolicy: 'Free cancellation up to 48 hours prior to check-in.',
    heroImage: 'https://images.unsplash.com/photo-1549294413-26f195200c16?auto=format&fit=crop&w=1200&q=80',
    images: [
      'https://images.unsplash.com/photo-1549294413-26f195200c16?auto=format&fit=crop&w=1000&q=80',
      'https://images.unsplash.com/photo-1571003123894-1f0594d2b5d9?auto=format&fit=crop&w=1000&q=80',
      'https://images.unsplash.com/photo-1520250497591-112f2f40a3f4?auto=format&fit=crop&w=1000&q=80',
    ],
    amenities: [
      'Lake Pichola Boat Arrival',
      'Private Semi-Private Pool Access',
      'Holistic Ayurvedic Spa',
      'Peacock Garden Walkways',
      'Royal Dining Pavilions',
      'Yoga & Meditation Classes',
    ],
    roomTypes: [
      {
        id: 'rt_obu_01',
        hotelId: 'htl_udaipur_03',
        name: 'Premier Room with Semi-Private Pool',
        description: 'Step directly from your private terrace into an azure moated swimming pool with serene lake and sanctuary views.',
        basePrice: 34000,
        maxGuests: 2,
        bedType: '1 King Bed',
        roomSize: '56 m² / 600 sq ft',
        totalRooms: 8,
        availableRooms: 3,
        images: [
          'https://images.unsplash.com/photo-1571003123894-1f0594d2b5d9?auto=format&fit=crop&w=800&q=80',
        ],
        amenities: ['Direct Pool Step-in', 'Lake View Terrace', 'Freestanding Victorian Bath', 'Daily Fresh Flowers'],
        hasFreeCancellation: true,
        breakfastIncluded: true,
      },
    ],
    reviews: [
      {
        id: 'rev_obu_01',
        hotelId: 'htl_udaipur_03',
        bookingId: 'BK-552199',
        customerName: 'Kavita Chawla',
        rating: 5,
        title: 'Beyond magical - pure heaven on earth',
        comment: 'Arriving by private boat across Lake Pichola sets the tone for an otherworldly stay. The staff anticipate your every desire with genuine warmth.',
        stayDate: 'July 2026',
        roomTypeName: 'Premier Room with Semi-Private Pool',
        createdAt: '2026-07-28',
        categories: { cleanliness: 5, staff: 5, comfort: 5, value: 5, location: 5 },
      },
    ],
  },
  {
    id: 'htl_goa_04',
    name: 'Alila Diwa South Goa',
    slug: 'alila-diwa-south-goa',
    tagline: 'Contemporary Goan tranquility amidst emerald paddy fields and Majorda beach',
    description: 'Immersed within 12 acres of serene paddy fields gently sloping toward the Arabian Sea, Alila Diwa Goa blends Goan-Portuguese vernacular with clean minimalist architecture. Relax by the iconic infinity pool that seamlessly merges with the emerald rice fields.',
    city: 'Goa',
    state: 'Goa',
    country: 'India',
    address: '48/10 Adao Waddo, Majorda, South Goa',
    postalCode: '403713',
    starRating: 5,
    averageRating: 4.79,
    totalReviews: 288,
    distanceToCenter: '5 mins to Majorda Beach',
    nearbyAttraction: 'Sunset Beach Trail',
    minPrice: 8900,
    checkInTime: '15:00',
    checkOutTime: '11:00',
    cancellationPolicy: 'Free cancellation up to 48 hours prior to check-in.',
    heroImage: 'https://images.unsplash.com/photo-1571896349842-33c89424de2d?auto=format&fit=crop&w=1200&q=80',
    images: [
      'https://images.unsplash.com/photo-1571896349842-33c89424de2d?auto=format&fit=crop&w=1000&q=80',
      'https://images.unsplash.com/photo-1507525428034-b723cf961d3e?auto=format&fit=crop&w=1000&q=80',
      'https://images.unsplash.com/photo-1540555700478-4be289fbecef?auto=format&fit=crop&w=1000&q=80',
    ],
    amenities: [
      'Paddy Field Infinity Pool',
      'Complimentary Beach Shuttle',
      'Spa Alila Natural Treatments',
      'Vivo All-Day Bistro',
      'Kids Club & Game Lounge',
      'Yoga Pavilion',
    ],
    roomTypes: [
      {
        id: 'rt_adg_01',
        hotelId: 'htl_goa_04',
        name: 'Terrace Room with Paddy View',
        description: 'Spacious ground or upper floor sanctuary with an expansive sun deck looking over endless green paddy fields.',
        basePrice: 8900,
        maxGuests: 2,
        bedType: '1 King Bed',
        roomSize: '44 m² / 475 sq ft',
        totalRooms: 20,
        availableRooms: 8,
        images: [
          'https://images.unsplash.com/photo-1540555700478-4be289fbecef?auto=format&fit=crop&w=800&q=80',
        ],
        amenities: ['Private Balcony Deck', 'Open Concept Bath', 'Artisanal Teas', 'Tropical Garden View'],
        hasFreeCancellation: true,
        breakfastIncluded: true,
      },
      {
        id: 'rt_adg_02',
        hotelId: 'htl_goa_04',
        name: 'The Diwa Private Club Suite',
        description: 'Exclusive resort-within-a-resort wing with dedicated private lap pool, personalized evening cocktails, and private cabana.',
        basePrice: 15400,
        maxGuests: 3,
        bedType: '1 King Bed',
        roomSize: '66 m² / 710 sq ft',
        totalRooms: 8,
        availableRooms: 2,
        images: [
          'https://images.unsplash.com/photo-1582719478250-c89cae4dc85b?auto=format&fit=crop&w=800&q=80',
        ],
        amenities: ['Diwa Club Pool Access', 'Daily Sunset Cocktails', 'Oversized Sun Loungers', 'Free Shuttle to Beach'],
        hasFreeCancellation: true,
        breakfastIncluded: true,
      },
    ],
    reviews: [
      {
        id: 'rev_adg_01',
        hotelId: 'htl_goa_04',
        bookingId: 'BK-772910',
        customerName: 'Arjun Sen',
        rating: 5,
        title: 'Peaceful, restorative Goan getaway',
        comment: 'Watching the sunset over the paddy field pool with a chilled cocktail was pure bliss. Far away from chaotic tourist crowds.',
        stayDate: 'August 2026',
        roomTypeName: 'Terrace Room with Paddy View',
        createdAt: '2026-08-11',
        categories: { cleanliness: 4.9, staff: 4.8, comfort: 5, value: 4.7, location: 4.8 },
      },
    ],
  },
  {
    id: 'htl_bengaluru_05',
    name: 'The Leela Palace Bengaluru',
    slug: 'the-leela-palace-bengaluru',
    tagline: 'Art Deco palace nestled within the lush Garden City',
    description: 'Inspired by the grand architectural heritage of the Mysore Royal Empire, The Leela Palace Bengaluru stands amid nine acres of cascading greenery. Featuring ornate gold-leaf domes, intricate stone carvings, and tranquil indoor waterfalls, this hotel defines regal business and leisure travel.',
    city: 'Bengaluru',
    state: 'Karnataka',
    country: 'India',
    address: '23 HAL Old Airport Road, Kodihalli, Bengaluru',
    postalCode: '560008',
    starRating: 5,
    averageRating: 4.91,
    totalReviews: 440,
    distanceToCenter: 'Central Business & Tech District',
    nearbyAttraction: 'Indiranagar Boutique Hub (5 mins)',
    minPrice: 10500,
    checkInTime: '14:00',
    checkOutTime: '12:00',
    cancellationPolicy: 'Free cancellation up to 48 hours prior to check-in.',
    heroImage: 'https://images.unsplash.com/photo-1578683010236-d716f9a3f461?auto=format&fit=crop&w=1200&q=80',
    images: [
      'https://images.unsplash.com/photo-1578683010236-d716f9a3f461?auto=format&fit=crop&w=1000&q=80',
      'https://images.unsplash.com/photo-1566073771259-6a8506099945?auto=format&fit=crop&w=1000&q=80',
    ],
    amenities: [
      'Mysore Royal Architecture',
      'Award-Winning Citrus Restaurant',
      'Leela Spa by ESPA',
      'Heated Outdoor Swimming Pool',
      '24/7 Business Concierge',
      'Lush Tropical Gardens',
    ],
    roomTypes: [
      {
        id: 'rt_lpb_01',
        hotelId: 'htl_bengaluru_05',
        name: 'Royal Premier Garden View',
        description: 'Finely appointed guest chamber with hand-tufted silk carpets, ornate archways, and serene views across lush palace lawns.',
        basePrice: 10500,
        maxGuests: 2,
        bedType: '1 King Bed',
        roomSize: '52 m² / 560 sq ft',
        totalRooms: 14,
        availableRooms: 5,
        images: [
          'https://images.unsplash.com/photo-1618773928121-c32242e63f39?auto=format&fit=crop&w=800&q=80',
        ],
        amenities: ['Garden View', 'Deep Soaking Tub', 'Pillow Menu', 'Executive Work Station'],
        hasFreeCancellation: true,
        breakfastIncluded: true,
      },
    ],
    reviews: [
      {
        id: 'rev_lpb_01',
        hotelId: 'htl_bengaluru_05',
        bookingId: 'BK-339281',
        customerName: 'Priya Iyer',
        rating: 5,
        title: 'Like living in a royal fairytale',
        comment: 'The architectural details and gardens make you forget you are in the heart of bustling Bangalore. Outstanding hospitality.',
        stayDate: 'September 2026',
        roomTypeName: 'Royal Premier Garden View',
        createdAt: '2026-09-04',
        categories: { cleanliness: 5, staff: 5, comfort: 4.9, value: 4.8, location: 4.9 },
      },
    ],
  },
  {
    id: 'htl_jaipur_06',
    name: 'Rambagh Palace Jaipur',
    slug: 'rambagh-palace-jaipur',
    tagline: 'The Jewel of Jaipur — Former residence of the Maharaja',
    description: 'Steeped in history, Rambagh Palace was the former residence of the Maharaja Sawai Man Singh II and his queen, Maharani Gayatri Devi. Known as the "Jewel of Jaipur", this authentic royal palace offers guests a rare encounter with Rajput elegance and royal hospitality.',
    city: 'Jaipur',
    state: 'Rajasthan',
    country: 'India',
    address: 'Bhawani Singh Road, Rambagh, Jaipur',
    postalCode: '302005',
    starRating: 5,
    averageRating: 4.97,
    totalReviews: 615,
    distanceToCenter: 'Central Civil Lines',
    nearbyAttraction: '10 mins to Hawa Mahal & City Palace',
    minPrice: 28000,
    checkInTime: '14:00',
    checkOutTime: '12:00',
    cancellationPolicy: 'Free cancellation up to 48 hours prior to check-in.',
    heroImage: 'https://images.unsplash.com/photo-1549294413-26f195200c16?auto=format&fit=crop&w=1200&q=80',
    images: [
      'https://images.unsplash.com/photo-1549294413-26f195200c16?auto=format&fit=crop&w=1000&q=80',
      'https://images.unsplash.com/photo-1571003123894-1f0594d2b5d9?auto=format&fit=crop&w=1000&q=80',
    ],
    amenities: [
      'Heritage Royal Grounds',
      'Polo Lounge & Bar',
      'Indoor & Outdoor Heated Pools',
      'Vintage Car Transfers',
      'Historic Royal Suites',
      'Jiva Grande Spa',
    ],
    roomTypes: [
      {
        id: 'rt_rpj_01',
        hotelId: 'htl_jaipur_06',
        name: 'Palace Room with Courtyard View',
        description: 'Exquisitely styled with royal tapestries, high canopied ceilings, and period furniture overlooking Mughal-style palace gardens.',
        basePrice: 28000,
        maxGuests: 2,
        bedType: '1 Royal King Bed',
        roomSize: '50 m² / 540 sq ft',
        totalRooms: 10,
        availableRooms: 4,
        images: [
          'https://images.unsplash.com/photo-1566665797739-1674de7a421a?auto=format&fit=crop&w=800&q=80',
        ],
        amenities: ['Mughal Garden View', 'Royal Turndown Service', 'Heritage Bath Amenities', 'Champagne Breakfast'],
        hasFreeCancellation: true,
        breakfastIncluded: true,
      },
    ],
    reviews: [],
  },
];

export const INITIAL_BOOKINGS: Booking[] = [
  {
    id: 'bkg_sample_01',
    bookingReference: 'BK-829104',
    customerId: 'usr_cust_01',
    hotelId: 'htl_chennai_01',
    hotelName: 'Grand Hyatt Chennai',
    hotelAddress: '32 Jawaharlal Nehru Road, Anna Nagar, Chennai',
    hotelHeroImage: 'https://images.unsplash.com/photo-1566073771259-6a8506099945?auto=format&fit=crop&w=600&q=80',
    roomTypeId: 'rt_ghc_01',
    roomTypeName: 'Deluxe City View King',
    roomNumber: '304',
    checkIn: '2026-10-15',
    checkOut: '2026-10-18',
    nights: 3,
    guestsCount: 2,
    guestInfo: {
      fullName: 'Ananya Sharma',
      email: 'ananya.sharma@example.com',
      phone: '+91 98765 43210',
      specialRequests: 'High floor, quiet room away from elevators.',
      estimatedArrival: '14:30',
    },
    priceBreakdown: {
      nights: 3,
      basePricePerNight: 6500,
      roomTotal: 19500,
      taxesAndGst: 3510,
      serviceFee: 500,
      grandTotal: 23510,
    },
    status: 'CONFIRMED',
    paymentStatus: 'COMPLETED',
    paymentMethod: 'Visa ending in •••• 4242',
    transactionReference: 'txn_mock_8291049281',
    createdAt: '2026-10-01T10:15:00.000Z',
  },
  {
    id: 'bkg_sample_02',
    bookingReference: 'BK-719342',
    customerId: 'usr_cust_01',
    hotelId: 'htl_goa_04',
    hotelName: 'Alila Diwa South Goa',
    hotelAddress: '48/10 Adao Waddo, Majorda, South Goa',
    hotelHeroImage: 'https://images.unsplash.com/photo-1571896349842-33c89424de2d?auto=format&fit=crop&w=600&q=80',
    roomTypeId: 'rt_adg_01',
    roomTypeName: 'Terrace Room with Paddy View',
    roomNumber: '112',
    checkIn: '2026-08-10',
    checkOut: '2026-08-13',
    nights: 3,
    guestsCount: 2,
    guestInfo: {
      fullName: 'Ananya Sharma',
      email: 'ananya.sharma@example.com',
      phone: '+91 98765 43210',
    },
    priceBreakdown: {
      nights: 3,
      basePricePerNight: 8900,
      roomTotal: 26700,
      taxesAndGst: 4806,
      serviceFee: 500,
      grandTotal: 32006,
    },
    status: 'COMPLETED', // Eligible for Verified Post-Stay Review!
    paymentStatus: 'COMPLETED',
    paymentMethod: 'Mastercard ending in •••• 8821',
    transactionReference: 'txn_mock_7193421102',
    createdAt: '2026-08-01T09:00:00.000Z',
    hasReview: false,
  },
];
