export * from './hotels.module';
export * from './hotels.service';
export * from './hotels.controller';
export * from './authorization/hotel-authorization.service';
export * from './dto/create-hotel.dto';
export * from './dto/update-hotel.dto';
export * from './dto/query-hotels.dto';
export * from './dto/assign-manager.dto';
export * from './types/paginated-hotels.type';
