import {
  Controller,
  Get,
  Post,
  Param,
  Body,
  Query,
  Headers,
  UseGuards,
  HttpCode,
  HttpStatus,
  ParseUUIDPipe,
} from '@nestjs/common';
import {
  ApiTags,
  ApiOperation,
  ApiResponse,
  ApiBearerAuth,
  ApiHeader,
  ApiParam,
} from '@nestjs/swagger';
import { PaymentsService } from './payments.service';
import { CreatePaymentDto } from './dto/create-payment.dto';
import { QueryPaymentsDto } from './dto/query-payments.dto';
import { PaymentResponseDto } from './types/payment-response.type';
import {
  JwtAuthGuard,
  RolesGuard,
  Roles,
  CurrentUser,
} from '../../common';
import { UserRole } from '../auth/types/user-role.enum';
import type { AuthenticatedUser } from '../auth/types/authenticated-user.type';

@ApiTags('Payments & Payment Attempts')
@ApiBearerAuth('JWT-auth')
@Controller('payments')
export class PaymentsController {
  constructor(private readonly paymentsService: PaymentsService) {}

  @Post()
  @UseGuards(JwtAuthGuard, RolesGuard)
  @Roles(UserRole.CUSTOMER, UserRole.ADMIN)
  @HttpCode(HttpStatus.CREATED)
  @ApiOperation({
    summary: 'Process payment attempt for reservation',
    description:
      'Creates or retries a payment attempt for a pending reservation. ' +
      'Guarantees strict database-level idempotency via Idempotency-Key. ' +
      'Authoritative payment amount is derived strictly from Booking.totalAmountCents. ' +
      'Transitions booking to CONFIRMED on success.',
  })
  @ApiHeader({
    name: 'Idempotency-Key',
    required: true,
    description:
      'Unique UUID or string generated by client to guarantee exactly-once processing.',
    example: '8c4c6f4e-202610-001',
  })
  @ApiResponse({
    status: 201,
    description: 'Payment processed or existing idempotent result replayed.',
    type: PaymentResponseDto,
  })
  @ApiResponse({
    status: 400,
    description: 'Booking not payable, invalid state, or missing Idempotency-Key.',
  })
  @ApiResponse({
    status: 403,
    description: 'Unauthorized customer or manager attempting payment on another user reservation.',
  })
  @ApiResponse({
    status: 404,
    description: 'Booking not found.',
  })
  @ApiResponse({
    status: 409,
    description:
      'Payment already completed, Idempotency-Key reused across bookings, or payment currently in progress.',
  })
  async processPayment(
    @CurrentUser() user: AuthenticatedUser,
    @Body() dto: CreatePaymentDto,
    @Headers('idempotency-key') idempotencyKey?: string,
  ): Promise<PaymentResponseDto> {
    return this.paymentsService.processPayment(user, dto, idempotencyKey);
  }

  @Get(':id')
  @UseGuards(JwtAuthGuard)
  @ApiOperation({
    summary: 'Get payment details by ID',
    description:
      'Retrieves the logical payment and its full historical ledger of payment attempts. ' +
      'Customers can only view their own payments. Managers are forbidden.',
  })
  @ApiParam({
    name: 'id',
    type: 'string',
    format: 'uuid',
    description: 'Unique UUID v4 of the Payment record',
  })
  @ApiResponse({
    status: 200,
    description: 'Payment details retrieved successfully.',
    type: PaymentResponseDto,
  })
  @ApiResponse({
    status: 403,
    description: 'Forbidden: customer cannot view another user payment, and managers cannot view customer payments.',
  })
  @ApiResponse({
    status: 404,
    description: 'Payment record not found.',
  })
  async getPaymentById(
    @CurrentUser() user: AuthenticatedUser,
    @Param('id', ParseUUIDPipe) id: string,
  ): Promise<PaymentResponseDto> {
    return this.paymentsService.getPaymentById(user, id);
  }

  @Get()
  @UseGuards(JwtAuthGuard)
  @ApiOperation({
    summary: 'List payment records',
    description:
      'Returns paginated payment records. Customers only see their own payments. ' +
      'Admins can view all payments or filter by bookingId. Managers are forbidden.',
  })
  @ApiResponse({
    status: 200,
    description: 'Paginated list of payments retrieved.',
  })
  @ApiResponse({
    status: 403,
    description: 'Forbidden: Managers cannot access customer payments.',
  })
  async getPayments(
    @CurrentUser() user: AuthenticatedUser,
    @Query() query: QueryPaymentsDto,
  ) {
    return this.paymentsService.getPayments(user, query);
  }
}
